featurized_data_path: data/05_model_input/featurized_data

train_params:
  batch_size: 128
  epochs: 200

split_params:
  label: 'RuleFive'
  X_column: 'FP'
  val_size: 0.1
  test_size: 0.1

n_ATC_classes: 15

# Fingerprint parameters
fingerprint_radius: 2
fingerprint_n_bits: 2048

# Number of ATC classes (for model)
n_atc_classes: 15
